### ISSUE TITLE
Compte Rendue 1

### ISSUE THREAD

**Issue by VincentGauweiler** [Saufian/projet-echec-et-pat#26]
Pour le premier compte-rendu, vous réaliserez une « conception technique » de votre application.
Cela se traduira par :
- une présentation de ce que vous allez créer ;
- une maquette du produit final illustrant la présentation ci-dessus ;
- la rédaction des différentes étapes de développements à réaliser ;
- une priorisation des tâches à réaliser ;
- une schématisation du processus applicatif ;
- la prévision de la charge de travail d’ici le prochain compte-rendu.

**Comment by Tsunayosh** [comment]
Dans la maquette je dois préciser tout le blabla du genre instructions, crédits etc...
