### ISSUE TITLE
Statut du code

### ISSUE THREAD

**Issue by bbailleux** [Saufian/projet-echec-et-pat#42]
Attention, l'expression « libre de droits » n'est pas significative pour décrire le statut du code publié.

Voir par exemple [cet article](https://www.journaldunet.com/developpeur/expert/36330/logiciel-libre-ne-signifie-pas-libre-de-droits.shtml) :
« [...] Les logiciels libres ne sont ni libres de droits, ni tombés dans le domaine public, contrairement à ce que certains ont pu affirmer. Ce sont bien des œuvres couvertes par le droit de la propriété intellectuelle. Leur utilisation est régie par des licences. [...] »

Il serait donc judicieux de :
- choisir une licence (commencer par l'article [Wikipedia](https://fr.wikipedia.org/wiki/Licence_libre) – je peux aider, aussi)
- Ajouter un `LICENSE.txt` (oui, le nom est en anglais) et **insérer des en-têtes** de fichiers (voir [cette réponse SO](https://stackoverflow.com/questions/3051651/open-source-licence-header-on-each-source-file-or-a-single-copying-or-both#3051855))

**Comment by bbailleux** [comment]
NB : oubli de ma part.
Déterminer qui est le détenteur du _Copyright_ : l'école ou les auteurs individuels

**Comment by Saufian** [comment]
Je ne pensais pas que tu le verrais aussi vite...

**Comment by bbailleux** [comment]
> Je ne pensais pas que tu le verrais aussi vite...

Hé hé : c'est une partie de mon job ;-)
Sérieusement : ce n'est pas très compliqué à trancher, et c'est « risqué » de laisser trainer.
Je peux aider pour faire le choix de licence si Open Source.

BTW : j'ai vu des fichiers binaires dans le dépôt Git ! WTF ?

**Comment by bbailleux** [comment]
> Je ne pensais pas que tu le verrais aussi vite...

Hé hé : c'est une partie de mon job ;-)
Sérieusement : ce n'est pas très compliqué à trancher, et c'est « risqué » de laisser trainer.
Je peux aider pour faire le choix de licence si Open Source.

BTW : j'ai vu des fichiers binaires (pas des images, des documents bureautiques) dans le dépôt Git ! WTF ?

**Comment by Saufian** [comment]
On pense partir sur une licence open source, la "GNU GENERAL PUBLIC LICENSE Version 3"
Mais on ne sait pas ce que l'on doit faire en pratique après avoir fait ce choix, est ce que tu peux nous aider sur ce point ?

**Comment by bbailleux** [comment]
Je vois les choses comme suit :
1. ajouter un fichier LICENSE.txt avec le texte intégral de la licence à la racine du projet (oui, le nom est en anglais, et je suggère de mettre la version anglaise du texte de la licence, car c'est la seule à avoir été validée - une traduction reste de toute façon accessible pour aider à sa compréhension). Si vous tenez à une licence valide et en français, regardez ce que propose la _CeCILL_ (https://cecill.info/)
2. Ajouter à _chaque_ fichier de code un en-tête comme décrit dans le dernier paragraphe du texte de la licence
3. Ajouter une mention à la licence choisie dans le README.md

Texte à ajouter (une fois les sections encadrées par `<` et `>` complétées) en tête de chaque fichier :

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
